#!/bin/sh
# Set permissions for /config directory and its contents

chown -R nixos:docker /mnt/unraid/homelab

find /mnt/unraid/homelab -type d -exec chmod 770 {} \;
find /mnt/unraid/homelab -type f -exec chmod 660 {} \;

chmod +x /mnt/unraid/homelab/scripts/*
