#!/bin/sh
# Set permissions for /config directory and its contents

chown -R 1000:100 /mnt/unraid/homelab

find /mnt/unraid/homelab -type d -exec chmod 700 {} \;
find /mnt/unraid/homelab -type f -exec chmod 600 {} \;

chmod +x /mnt/unraid/homelab/scripts/*
