###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: auto

default_redirection_url: https://google.com/

server:
  address: tcp4://:9091

log:
  level: debug

totp:
  issuer: benfeather.com
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  file:
    path: /config/users.yml
    password:
      algorithm: argon2id
      salt_length: 16
      parallelism: 8
      memory: 1024
      iterations: 1
      key_length: 32

access_control:
  default_policy: deny
  rules:
    - domain: "auth.benfeather.com"
      policy: bypass
    - domain: "*.benfeather.com"
      policy: one_factor

session:
  name: authelia_session
  # secret: unsecure_session_secret
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: benfeather.com 

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  local:
    path: /config/db.sqlite
  
notifier:
  disable_startup_check: true #true/false
  smtp:
    username: youremail@gmail.com #your email address
    password: Y0uRp@55W0rD! #your email password
    host: smtp.gmail.com #email smtp server
    port: 587 #email smtp port
    sender: youremail@gmail.com
    identifier: localhost
    subject: "[Authelia] {title}" #email subject
    startup_check_address: youremail@gmail.com
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
